### ISSUE TITLE
Some fields of DesignDoc should be optional

### ISSUE THREAD

**Issue by ionos** [gnieh/sohva#72]
CouchDB may not return all the fields currently needed to create a DesignDoc instance, hence calls to `design.getDesignDocument` may fail.

```
[error] Exception in thread "main" spray.json.DeserializationException: Object is missing required member 'updates'
[error] 	at spray.json.package$.deserializationError(package.scala:23)
[error] 	at spray.json.ProductFormats$class.fromField(ProductFormats.scala:60)
[error] 	at gnieh.sohva.SohvaProtocol$.fromField(SohvaProtocol.scala:282)
[error] 	at spray.json.ProductFormatsInstances$$anon$9.read(ProductFormatsInstances.scala:262)
[error] 	at spray.json.ProductFormatsInstances$$anon$9.read(ProductFormatsInstances.scala:242)
[error] 	at gnieh.sohva.SohvaProtocol$$anon$1.read(SohvaProtocol.scala:59)
[error] 	at gnieh.sohva.SohvaProtocol$$anon$1.read(SohvaProtocol.scala:59)
[error] 	at spray.json.JsValue.convertTo(JsValue.scala:31)
[error] 	at gnieh.sohva.Design.gnieh$sohva$Design$$designDoc(Design.scala:345)
[error] 	at gnieh.sohva.Design$$anonfun$getDesignDocument$1$$anonfun$apply$2.apply(Design.scala:70)
[error] 	at gnieh.sohva.Design$$anonfun$getDesignDocument$1$$anonfun$apply$2.apply(Design.scala:70)
[error] 	at scala.Option.map(Option.scala:146)
[error] 	at gnieh.sohva.Design$$anonfun$getDesignDocument$1.apply(Design.scala:70)
[error] 	at gnieh.sohva.Design$$anonfun$getDesignDocument$1.apply(Design.scala:68)
[error] 	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
[error] 	at scala.util.Try$.apply(Try.scala:192)
[error] 	at scala.util.Success.map(Try.scala:237)
[error] 	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
[error] 	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
[error] 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
[error] 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
[error] 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
[error] 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
[error] 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
[error] 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
[error] 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
[error] 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:409)
[error] 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[error] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[error] 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[error] 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] Caused by: java.util.NoSuchElementException: key not found: updates
[error] 	at scala.collection.MapLike$class.default(MapLike.scala:228)
[error] 	at scala.collection.AbstractMap.default(Map.scala:59)
[error] 	at scala.collection.MapLike$class.apply(MapLike.scala:141)
[error] 	at scala.collection.AbstractMap.apply(Map.scala:59)
[error] 	at spray.json.ProductFormats$class.fromField(ProductFormats.scala:57)
[error] 	... 30 more
```

**Comment by satabin** [comment]
This should be solved now. a new snapshot version `2.0.1-SNAPSHOT` has been pushed to snapshot repository with the fix. Let me know if the problem is still open.
